```{r}
bigmart_train <- read.csv('Data_Train.csv', sep = ';')
str(bigmart_train)
names(bigmart_train)
summary(bigmart_train)
bigmart_train
duplicated(bigmart_train$Product_ID)

```
## (SOAL 1) sales characteristics 
```{r}
table(bigmart_train$Product_Type)
table(bigmart_train$Outlet_ID)
by(bigmart_train$Product_Type, bigmart_train$Outlet_ID, summary)
sorted_data = bigmart_train[order(bigmart_train[,12], bigmart_train[,7]),]
summary(bigmart_train$Outlet_ID)
sorted_data_1 = split(sorted_data, sorted_data$Outlet_ID)
out013 = sorted_data_1$OUT013
out018 = sorted_data_1$OUT018
out035 = sorted_data_1$OUT035
out046 = sorted_data_1$OUT046
out049 = sorted_data_1$OUT049

aggregate(out013$Product_Outlet_Sales, by=list(Category=out013$Product_Type), FUN = sum)
aggregate(out018$Product_Outlet_Sales, by=list(Category=out018$Product_Type), FUN = sum)
aggregate(out035$Product_Outlet_Sales, by=list(Category=out035$Product_Type), FUN = sum)
aggregate(out046$Product_Outlet_Sales, by=list(Category=out046$Product_Type), FUN = sum)
aggregate(out049$Product_Outlet_Sales, by=list(Category=out049$Product_Type), FUN = sum)

```

## (SOAL 2) Percentage of total display area by each store for each product type
```{r}
aggregate(out013$Product_Visibility, by=list(Category=out013$Product_Type), FUN=sum)
aggregate(out018$Product_Visibility, by=list(Category=out018$Product_Type), FUN=sum)
aggregate(out035$Product_Visibility, by=list(Category=out035$Product_Type), FUN=sum)
aggregate(out046$Product_Visibility, by=list(Category=out046$Product_Type), FUN=sum)
aggregate(out049$Product_Visibility, by=list(Category=out049$Product_Type), FUN=sum)
```

## (SOAL 3) Relationship between the percentages
```{r}
library(ggplot2)
productSeafood = bigmart_train$Product_Type == "Seafood"
seafoodSelected = bigmart_train[productSeafood, c("Product_Visibility", "Product_Outlet_Sales")]
seafoodSelected

lm(seafoodSelected$Product_Visibility ~ seafoodSelected$Product_Outlet_Sales)

ggplot(seafoodSelected, aes(x =Product_Visibility, y = Product_Outlet_Sales))+
  geom_point()+
  geom_smooth(method = 'lm', formula = y~x)


summary(bigmart_train$Product_Visibility)
ggplot(bigmart_train, aes(x=Product_Visibility, y=Product_Outlet_Sales))+
  geom_point()+
  facet_wrap(~Product_Type)+
  geom_smooth(method = 'lm', formula = y~x)
list_type = unique(bigmart_train[c("Product_Type")])$Product_Type
list_type
#tes <- subset(bigmart_train ,Product_Type == list_type[])
#tes
for(i in 1:16){
  tes <- subset(bigmart_train ,Product_Type == list_type[i])
  print(cor(tes$Product_Visibility, tes$Product_Outlet_Sales, method="kendall"))
  print(list_type[i])
}
```

## (SOAL 4) Mean of sales outcome for each store age category
```{r}
list_age = unique(bigmart_train[c("Outlet_Establishment")])$Outlet_Establishment
list_age
for(i in 1:5){
  data_by_date <- subset(bigmart_train, Outlet_Establishment=list_age[i])
  print(aggregate(data_by_date$Product_Outlet_Sales, by=list(Category=data_by_date$Outlet_Establishment), FUN=mean))
}
```


## (SOAL 5) Characteristics of Low Fat and Regular product sales for each store.
```{r}
regularSales = bigmart_train[bigmart_train$Product_Fat_Content == "Regular",c("Outlet_ID", "Product_Outlet_Sales", "Product_Fat_Content")]

bigmart_train

lowFatSales= bigmart_train[bigmart_train$Product_Fat_Content == "Low Fat",c("Outlet_ID", "Product_Outlet_Sales", "Product_Type")]

regularSales

aggregate(Product_Outlet_Sales ~ Outlet_ID, regularSales, mean)
aggregate(Product_Outlet_Sales ~ Outlet_ID, lowFatSales, mean)

ggplot(regularSales, aes(x = Outlet_ID, y = Product_Outlet_Sales))+
  geom_col(width = 0.5)

ggplot(lowFatSales, aes(x = Outlet_ID, y=Product_Outlet_Sales))+
  geom_col(width = 0.5)

```

## (SOAL 6) Is there a difference between the sales for each type of store location?
```{r}
aggregate(Product_Outlet_Sales ~ Outlet_Location_Type, bigmart_train, sum)
aggregate(Product_Outlet_Sales ~ Outlet_Location_Type, bigmart_train, mean)
aggregate(Product_Outlet_Sales ~ Outlet_Location_Type, bigmart_train, sum)/aggregate(Product_Outlet_Sales ~ Outlet_Location_Type, bigmart_train, mean)
tier_1 = bigmart_train[bigmart_train$Outlet_Location_Type == "Tier 1", c("Product_Outlet_Sales")]
tier_2 = bigmart_train[bigmart_train$Outlet_Location_Type == "Tier 2", c("Product_Outlet_Sales")]
tier_3 = bigmart_train[bigmart_train$Outlet_Location_Type == "Tier 3", c("Product_Outlet_Sales")]

dati = c(tier_1, tier_2, tier_3)
length(tier_1)
length(tier_2)
length(tier_3)
x <- c()
for(i in 1:length(tier_1))
{
  x <- append(x, 'a')  
}
for(i in 1:length(tier_2))
{
  x <- append(x, 'b')
}
for(i in 1:length(tier_3))
{
  x <- append(x, 'c')
}
x
anova(lm(formula=dati ~ x))
```


